import { Metadata } from "next"
export const metadata: Metadata = {
  title: "Tasks Submission",
  description: "Generated by create next app",
};
function page() {
    
  return (
    <div>page</div>
  )
}

export default page